#pragma once

#define TSC_MOUSE_BUTTON_1         0
#define TSC_MOUSE_BUTTON_2         1
#define TSC_MOUSE_BUTTON_3         2
#define TSC_MOUSE_BUTTON_4         3
#define TSC_MOUSE_BUTTON_5         4
#define TSC_MOUSE_BUTTON_6         5
#define TSC_MOUSE_BUTTON_7         6
#define TSC_MOUSE_BUTTON_8         7
#define TSC_MOUSE_BUTTON_LAST      TSC_MOUSE_BUTTON_8
#define TSC_MOUSE_BUTTON_LEFT      TSC_MOUSE_BUTTON_1
#define TSC_MOUSE_BUTTON_RIGHT     TSC_MOUSE_BUTTON_2
#define TSC_MOUSE_BUTTON_MIDDLE    TSC_MOUSE_BUTTON_3